### ISSUE TITLE
Documented connect statement doesn't work.

### ISSUE THREAD

**Issue by nabeards** [plus3network/hyena#5]
Using the documented connect statement:

```
hyena.connect(connection({
  user: "example",
  password: "example",
  database: "example"
}));
```

fails with error:

```
Error: You must suppy [sic] a connection string
```

Just installed everything through NPM, regular MySQL connections work fine. It looks like from the code you are expecting a string (index.js):

```
hyena.createConnection = function (dsnString, options, callback) {
  if ('string' !== typeof(dsnString)) {
    throw new Error('You must suppy a connection string');
  }
...
hyena.connect = hyena.createConnection;
```

In test/fixtures/seed.js, there is an example:

```
hyena.createConnection('mysql://'+mysql_user+'@localhost/hyena_test');
```

I need to connect via MySQL socket, so that doesn't work for me. Is the documented connect statement supposed to work? Am I missing something else?

Thanks,
Neil

**Comment by valerisuleo** [comment]
@nabeards thank you so much!
